singleQuote: true
tabWidth: 2
trailingComma: all
overrides:
  - files: ["*.ts", "*.mts", "*.js", "*.mjs", "*.cjs"]
    options:
      tabWidth: 4
  - files: ["*.yml", "*.yaml"]
    options:
      singleQuote: false

printWidth: 80
semi: true
plugins:
  - './node_modules/prettier-plugin-sort-imports/dist/index.js'
sortingMethod: 'alphabetical'
